### ISSUE TITLE
corrupted .mp4 files

### ISSUE THREAD

**Issue by yveshanoulle** [NateMccomb/TeslaCamViewer-legacy#1]
>Some TeslaCam .mp4 files get corrupt either while they are being saved or within the video >itself. Some video playback windows may not populate due to this reason.
The corrupted files I have seen, are 0 bytes. 
Looking for 0 bytes files,  might be a way to avoid having problems with them. (You still can't show them)

**Comment by NateMccomb** [comment]
Correct, some people still think it's the viewers fault until ask them to view the file in VLC/other player to verify that no, it's the file that is corrupted or shorter then 1 minute. My viewer has been able to handle this just fine and shows a black image for that video instead but that's what confuses everyone. Lets hope Tesla can fix this in an upcoming update and add more cameras.

**Comment by yveshanoulle** [comment]
Or shown an image: file corrupted.
