### ISSUE TITLE
Since Firmware 2019.24.4: Videos not navigatable

### ISSUE THREAD

**Issue by Kumasasa** [NateMccomb/TeslaCamViewer-legacy#11]
Since Tesla firmware 2019.24.4 videos cannot be stepped into / over.

When clicking an event, the there is only a frozen image of all three clips shown, when clicking on a certain clip, it will play unless trying to jump/skip some time.
Sounds weird, but cannot describe this better.

The reason is that the video clips are starting not at 0.0 seconds any more, but at -0.02 seconds, and that may disturb ffmpeg.

**Comment by NateMccomb** [comment]
I know exactly what you mean. 
I meant to post something to the main readme file yesterday, I also just got the Tesla 2019.24.4 update two days ago and something changed on Tesla's side on how they are encoding the videos. I'm currently working on a fix for this but will need a few days to work out the bugs.
Here is a Reddit post about other viewers having issues too at the update: 
https://old.reddit.com/r/teslamotors/comments/chpbsp/2019244_dashcam_video_not_playable_in_browser/

**Comment by Kumasasa** [comment]
Yeah, that's the root cause of the issue.
