### ISSUE TITLE
Class Not Registered Error when starting

### ISSUE THREAD

**Issue by germanmarky** [NateMccomb/TeslaCamViewer-legacy#12]
There was an error but we couldn't send a bug report to Nate because there is no internet access: 

An error occurred creating the form. See Exception.InnerException for details.  The error is: Class not registered (Exception from HRESULT: 0x80040154 (REGDB_E_CLASSNOTREG))

**Comment by germanmarky** [comment]
Fix is to add logic to MainForm.Designer.vb right after InitializeComponent() sub routine to check if Windows Media Features are installed:

If Microsoft.Win32.Registry.LocalMachine.OpenSubKey("HKLM\SOFTWARE\Microsoft\Active Setup\Installed Components\{22d6f312-b0f6-11d0-94ab-0080c74c7e95}") Is Nothing Then
            MsgBox("You need to have Windows Media Player Installed to run TeslaCam Viewer" + vbCrLf + "1. Open Apps and Features" + vbCrLf + "2. Click Programs and Features on the right" + vbCrLf + "3. Click Turn Windows features on or off" + vbCrLf + "4. Click the checkbox on Media Features", MsgBoxStyle.OkCancel, "ERROR")
            Me.Close()
            End
        Else
            ' Key existed
        End If

**Comment by germanmarky** [comment]
[PR#13](https://github.com/NateMccomb/TeslaCamViewer/pull/13) submitted for fix

**Comment by NateMccomb** [comment]
This was addressed and fixed in the 2019.35.5.0 update
