### ISSUE TITLE
H265 on HW3 on V10

### ISSUE THREAD

**Issue by dilorenzo1987** [NateMccomb/TeslaCamViewer-legacy#15]
Hi,

Can you confirm that on V10 HW3 is back using H264 instead of H265?

Regards

**Comment by NateMccomb** [comment]
I can only confirm V10 HW2.5 and it's still h264
![image](https://user-images.githubusercontent.com/9289783/66253163-c8376c80-e731-11e9-87e9-548e6a37d2a9.png)

**Comment by dilorenzo1987** [comment]
Check this:

https://teslamotorsclub.com/tmc/threads/fsd-computer-hw3-or-hw2-5-tracking-sheet.162348/
