### ISSUE TITLE
Network Path

### ISSUE THREAD

**Issue by dilorenzo1987** [NateMccomb/TeslaCamViewer-legacy#16]
Hi,

I archive all my Sentry Mode videos to a network path (UNC).
Unfortunately im unable to browse to that location using the current UI.
Custom Folder shows "Network" location but my NAS does not show up.

Can you add a feature to manually add a custom path?

Regards,
Fabio

**Comment by NateMccomb** [comment]
Have you tried mounting the NAS folder as a local drive? This might be one work around for the time being. I'll add to my to-do list the ability to specify a custom folder path.

**Comment by dilorenzo1987** [comment]
Thanks for the reply, 
Dont like network drives. :)

I manually edited the user.config as a workaround.

**Comment by NateMccomb** [comment]
Kudos on finding the user.config and editing it!
I just wrapped up with adding the ability to specify a network location for the next release of [TeslaCam Viewer II](https://github.com/NateMccomb/TeslaCamViewerII).
