### ISSUE TITLE
Crash when trying to export a video with 0.5 speed

### ISSUE THREAD

**Issue by Kumasasa** [NateMccomb/TeslaCamViewer-legacy#17]
```
29.09.2019 00:49:01 -  - Application ERROR - Ungültige Konvertierung von der Zeichenfolge .5 in Typ Double.
   bei Microsoft.VisualBasic.CompilerServices.Conversions.ToDouble(String Value, NumberFormatInfo NumberFormat)
   bei TeslaCam_Viewer.MainForm.GroupBoxRENDER_MouseEnter(Object sender, EventArgs e)
   bei System.Windows.Forms.Control.OnMouseEnter(EventArgs e)
   bei System.Windows.Forms.Control.WndProc(Message- m)
   bei System.Windows.Forms.GroupBox.WndProc(Message- m)
   bei System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message- m)
   bei System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```
Message translated: Invalid conversion from string .5 into type Double
Most probably because the ".5" isn't a valid floating point string  on a German Windows, because we use a comma as decimal separator.
A wild guess: Don't fill the drop down box with a fixed string "x .5"  but with a localized floating point number "x 0,5"
(If I had any knowledge in Windows VB programming I'd fix that in the source code, but I'm programming on C++ on Linux for embedded systems.)
<img width="231" alt="export" src="https://user-images.githubusercontent.com/12480900/66259270-4dad3200-e7af-11e9-957d-d0c7067d79c9.png">

**Comment by NateMccomb** [comment]
The decimal separator was the issue and this was addressed in [TeslaCam Viewer II](https://github.com/NateMccomb/TeslaCamViewerII)
