### ISSUE TITLE
crashes utility every time I click a sub folder in the saved or recent.

### ISSUE THREAD

**Issue by joshsinykin** [NateMccomb/TeslaCamViewer-legacy#2]
crashes utility every time I click a sub folder in the saved or recent.

**Comment by NateMccomb** [comment]
Have you downloaded the latest version 2019.25 or newer?
Is there an error message when it crashes? What's the build date of your Tesla? 
Newer Tesla's with HW3 FSD computers needs the h.265 codec installed. A link is in the readme doc. under install

**Comment by shantanuthatte** [comment]
Same thing is happening. Using 2019.25.3.2 with the codec installed.

**Comment by joshsinykin** [comment]
I was able to resolve my issue here. The problem is related to my AMD FirePro graphics card being automatically selected as the graphics processing instead of the Intel CPU GPU. Once I use the Intel GPU , the 0xc0000005 exception on the d3d9.dll goes away and the video displays just fine. Just wanted to pass this informational along.

**Comment by NateMccomb** [comment]
Thank you Josh for figuring thing out!
Here is a [link](https://support.serato.com/hc/en-us/articles/202305784-Changing-graphics-card-settings-to-use-your-dedicated-GPU-on-a-Windows-computer-) that I found for everyone else that will explain where to find these settings for most GPUs. 

For everyone else,
Please let me know if this solves your issue of when you first run TeslaCam Viewer and it crashes when a folder is first selected. Also let me know what settings you had to choose for it to work so others can follow.

**Comment by AntonLM** [comment]
This is not working for me. I tried the methods you linked to, but my computer (Win10 PC) does not seem to have to options I'm asked to set.

**Comment by shackrock** [comment]
Where do I set the graphics card?  I don't see it in settings.

**Comment by jasonyang-ee** [comment]
For those who still have issue, this maybe caused by the VLC download link provided in README is x32 version. But, you may need x64 version instead. Please make sure your VLC player matches to your OS system.
