### ISSUE TITLE
FSD H265 format files

### ISSUE THREAD

**Issue by mrdadmiller** [NateMccomb/TeslaCamViewer-legacy#3]
My 6/19 build date (FSD hardware) Model 3 with 2019.15.103 firmware makes H265 formatted  .mp4 video files. VLC is the only Windows 10 PC tool that I am able to successfully use to view individual .mp4 video files. I have had no success in using “TeslaCam Viewer”. It displays a black screens and fails.

**Comment by NateMccomb** [comment]
Try installing the Microsoft H.265 codec (HEVC Video Extensions)
https://www.microsoft.com/en-us/p/hevc-video-extensions-from-device-manufacturer/9n4wgh0z6vhq?irgwc=1&OCID=AID681541_aff_7593_159229&tduid=%28ir_wJC0gNTClQca0BAzqwxkEXPhUkjTGXQhW1412Y0%29%287593%29%28159229%29%28%29%28UUwpUdUnU56397YYwYd%29&irclickid=wJC0gNTClQca0BAzqwxkEXPhUkjTGXQhW1412Y0&activetab=pivot%3Aoverviewtab

**Comment by mrdadmiller** [comment]
Nate, Installing the Microsoft H.265 codec installing the Microsoft H.265 codec fixed my problem.  Thank you, Dave
