### ISSUE TITLE
Release Tracking

### ISSUE THREAD

**Issue by gohamstergo** [NateMccomb/TeslaCamViewer-legacy#4]
Hey,

When new releases are available, could you add them as a "release" on github? Users are able to subscribe to new releases, but if only the readme links are being updated, no notice is sent :)

Could just use a text file, just enough that the release is triggered.

Thanks for a cool app.

**Comment by NateMccomb** [comment]
Thanks for let me know about this feature, I'm still very new to GitHub and learning the ins and outs!
TeslaCam Viewer is my first production application that I have posted and continuously updating on GitHub, so I'm still learning how to get new info out to users. Now that I know this exist, I'll be sure to add new updates to the release tab!
