### ISSUE TITLE
Automate this without a gui?

### ISSUE THREAD

**Issue by bahree** [NateMccomb/TeslaCamViewer-legacy#5]
Love what you have done and I have to be honest, haven't seen VB in a looooong time, so kudos for that! 👍 

Not really an issue, but more of a question / discussion and sorry could not find another option to post this.

I am using teslausb to automatically pull the videos from the car to my NAS (see https://github.com/marcone/teslausb) and was wondering if you explored the idea of automating this somewhat so one doesn't have to use the GUI - something like what https://github.com/ehendrix23/tesla_dashcam is doing. 

Thanks.

**Comment by NateMccomb** [comment]
Thanks, I've worked with VB for 17+ years and thought about going with C# but I haven't used it enough to be comfortable debugging issues as I run into them. Python would have been another option but requires users to get the back end up and running on their own. I figured a single executable that could be easily ran on any Windows PC or portable from a thumb drive would be easier for the end users using my viewer. 

I've thought about automating some of the things but most Sentry Mode triggers are false alarms and would be a waste of time and CPU resources IMO plus like you mentioned, others have already coded for this. The reason I built the app was to find and view Sentry Mode triggered events as quickly as possible either from the thumb drive or from a NAS after its been uploaded using TeslaUSB.
