### ISSUE TITLE
Feature request: OSX support

### ISSUE THREAD

**Issue by the-mace** [NateMccomb/TeslaCamViewer-legacy#6]
I know this is a big ask given the current VB approach, but no Windows here. 

Would be great to see something that worked for OSX.

**Comment by NateMccomb** [comment]
Sorry, I don't own a new enough Mac to even develop a version for OSX. 
Check out Kartik @itskrtk who is working on a similar Mac version.
https://twitter.com/itskrtk/status/1143665666102374400
