### ISSUE TITLE
.NET Framwork won't install

### ISSUE THREAD

**Issue by jhogoboom** [NateMccomb/TeslaCamViewer-legacy#8]
Installer says it needs .NET framework 3.5.  Tries to download it, but the computer has a much later version (6.2).  Any fix for this?

**Comment by NateMccomb** [comment]
Under 'Control Panel' > 'Programs and Features' - Click 'Turn Windows features on or off' 
Is .NET Framework 3.5 installed? There should be a black box or check mark letting you know it's installed.
![image](https://user-images.githubusercontent.com/9289783/60402975-0175a480-9b65-11e9-8f54-fd04b5a59955.png)

**Comment by jhogoboom** [comment]
Thanks. Will check when I get hone later!  Hope I can get it working. Seems like a great viewer!!



Jack Hogoboom

On Jun 30, 2019, at 6:30 PM, NateMccomb <notifications@github.com> wrote:

Under 'Control Panel' > 'Programs and Features' - Click 'Turn Windows features on or off'
Is .NET Framework 3.5 installed? There should be a black box or check mark letting you know it's installed.

**Comment by jhogoboom** [comment]
That fixed it, although the steps are a little different in Windows 10 (at least my configuration). Sending you PayPal. 

Thanks!!

Jack Hogoboom


On Jun 30, 2019, at 6:30 PM, NateMccomb <notifications@github.com> wrote:

Under 'Control Panel' > 'Programs and Features' - Click 'Turn Windows features on or off'
Is .NET Framework 3.5 installed? There should be a black box or check mark letting you know it's installed.

**Comment by NateMccomb** [comment]
Awesome, Glad you got it working and thank you!
